config/routes.rb
Rails.application.routes.draw do
  # GET /tasks
  get  "tasks", to: "tasks#index"
  get  "tasks/new", to: "tasks#new"
  post "tasks", to: "tasks#create"
  get  "tasks/:id", to: "tasks#show", as: "task" # task_path(ID_OF_TASK OR INSTANCE_OF_TASK)
  get "tasks/:id/edit", to: "tasks#edit", as: "task_edit"
  patch  "tasks/:id", to: "tasks#update"
  delete "tasks/:id", to: "tasks#destroy", as: "task_destroy"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
 before_action :find_task , only: [:show, :edit, :update, :destroy]
 # you add the before_action when you want to acces the method that you
 # created since its been repeated in the controller inside the other methods.
 def index
    # GET /tasks
    @tasks = Task.all
 end

 def show
    #@task = Task.find(params[:id])
    # GET /tasks/:id
 end

  def new
    @task = Task.new
    # GET /tasks/new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to task_path(@task)
    # POST /tasks
  end

  def edit
    #@task = Task.find(params[:id])
    # GET /tasks/:id/edit
  end

  def update
    # @task = Task.find(params[:id]) u dont need to use it
    # anymore since you are stating it in the before_action
    @task.update(task_params)
    redirect_to task_path(@task)
    # PATCH /tasks/:id
  end

  def destroy
    @task.destroy
    redirect_to tasks_path
    # DELETE /tasks/:id
  end

  private
  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
  def find_task
    @task = Task.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :details %>
  <%= f.text_field :details%>
  <%= f.label :completed %>
  <%= f.check_box :completed%>
  <%= f.submit %>

<% end %>

app/views/tasks/edit.html.erb
<%= render 'form', task: @task %>

app/views/tasks/index.html.erb
<h1>My Tasks</h1>

  <% @tasks.each do |task| %>
    <div>
    <input class="form-check-input" type="checkbox"<%= "checked" if task.completed %>

    <%= link_to task.title, task_path(task) %>
    <%= link_to "edit", task_edit_path(task) %>
    <%= link_to "destroy", task_destroy_path(task), method: :delete %>

  </div>
  <% end %>
<%= link_to "create a task", tasks_new_path %>

app/views/tasks/new.html.erb
<%= render 'form', task: @task %>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>

<p><%= @task.details %></p>

<%= link_to "Go back!", tasks_path %>
<%= link_to "edit", task_edit_path(@task) %>
<%= link_to "destroy", task_destroy_path(@task), method: :delete%>